{{ if eq .chezmoi.os "linux" }}

[".config/xremap/xremap-my-eucalyn"]
    type = "git-repo"
    url = "https://github.com/Hiroya-W/xremap-my-eucalyn.git"
    refreshPeriod = "0"

{{   if contains "i3" (output "printenv" "DESKTOP_SESSION") }}

[".config/polybar_themes/polybar-adapta-theme"]
    type = "git-repo"
    url = "https://github.com/Hiroya-W/polybar-adapta-theme.git"
    refreshPeriod = "0"

[".config/polybar_themes/polybar-sequoia-theme"]
    type = "git-repo"
    url = "https://github.com/Hiroya-W/polybar-sequoia-theme.git"
    refreshPeriod = "0"

[".config/rofi_themes/rofi"]
    type = "git-repo"
    url = "https://github.com/Hiroya-W/rofi.git"
    refreshPeriod = "0"

["Pictures/backgrounds/wp8679761.jpg"]
    type = "file"
    url = "https://wallpapercave.com/wp/wp8679761.jpg"
    refreshPeriod = "0"

["Pictures/backgrounds/sakura.jpg"]
    type = "file"
    url = "https://raw.githubusercontent.com/Stardust-kyun/dotfiles/6e4c23b3d2840c7c531d87b2e3eda19aef39c92b/home/.config/awesome/colors/sakura/sakura.jpg"
    refreshPeriod = "0"

{{   end }}
{{ end }}
