#!/bin/bash

## nitrogen
### Download background image

BACKGROUNDS_DIR="$HOME/Pictures/backgrounds"

declare -A BACKGROUND_IMGS=(
    ["wp8679761.jpg"]="https://wallpapercave.com/wp/wp8679761.jpg"
    ["sakura.jpg"]="https://raw.githubusercontent.com/Stardust-kyun/dotfiles/6e4c23b3d2840c7c531d87b2e3eda19aef39c92b/home/.config/awesome/colors/sakura/sakura.jpg"
)

if [ ! -d "$BACKGROUNDS_DIR" ]; then
    mkdir -p "$BACKGROUNDS_DIR"
fi

for img in "${!BACKGROUND_IMGS[@]}"; do
    wget -O "$BACKGROUNDS_DIR/${img}" "${BACKGROUND_IMGS[${img}]}"
done

## i3wm
i3-msg reload
