[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = '''
  let g:tokyonight_style = "night"
  colorscheme tokyonight
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = ['nvim-web-devicons', 'tokyonight.nvim']
hook_add = '''
    source ~/.config/nvim/plugins/lualine.vim
'''

[[plugins]]
repo = "akinsho/bufferline.nvim"

[[plugins]]
repo='neoclide/coc.nvim'
merged=0
rev='release'
hook_add = '''
  source ~/.config/nvim/plugins/coc.vim
'''

[[plugins]]
repo = "kdheepak/lazygit.nvim"
hook_add = """
    let g:lazygit_floating_window_winblend = 0 " transparency of floating window
    let g:lazygit_floating_window_scaling_factor = 0.9 " scaling factor for floating window
    let g:lazygit_floating_window_corner_chars = ['╭', '╮', '╰', '╯'] " customize lazygit popup window corner characters
    let g:lazygit_floating_window_use_plenary = 0 " use plenary.nvim to manage floating window if available
    let g:lazygit_use_neovim_remote = 1 " fallback to 0 if neovim-remote is not installed
    " setup mapping to call :LazyGit
    nnoremap <silent> <leader>gs :LazyGit<CR>
"""
