[[plugins]]
repo = 'rcarriga/nvim-notify'
on_lua = 'notify'
on_source = '''
lua vim.notify = require('notify')
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim") && !has("win32")'
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = '''
  source ~/.config/nvim/plugins/treesitter.lua
'''

[[plugins]]
repo = "shougo/deol.nvim"
hook_add = """
  nnoremap <silent><C-t> :<C-u>Deol -split=floating<CR>
  tnoremap <ESC>   <C-\><C-n>
"""

[[plugins]]
repo = "rust-lang/rust.vim"
on_ft = "rust"
